### ISSUE TITLE
Improve error message for pymech readers when mesh not supported

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#184]
see https://github.com/snek5000/snek5000/issues/140#issuecomment-1285195453

**Comment by ashwinvis** [comment]
It will be fixed in https://github.com/eX-Mech/pymech/issues/65. Is that good enough?

**Comment by paugier** [comment]
As soon as https://github.com/eX-Mech/pymech/issues/65 is fixed, we can close this issue yes.

**Comment by ashwinvis** [comment]
Fixed in pymech. Here is an example:

```py
~/.local/scratch/tmp/examples_snek_phill/short/phill_run_12x10x8_V1.x1.x1._2022-11-14_22-45-40/session_00
pymech-pypy ❯ python -c 'import pymech as pm; pm.open_dataset("phill0.f00010")'
Traceback (most recent call last):
  File "/home/avmo/Sources/snek5000/pymech/pymech/dataset.py", line 77, in _open_nek_dataset
    elem_dsets = [
  File "/home/avmo/Sources/snek5000/pymech/pymech/dataset.py", line 78, in <listcomp>
    xr.Dataset.load_store(store).set_coords(store.axes) for store in elem_stores
  File "/home/avmo/.pyenv/versions/pymech/lib/python3.9/site-packages/xarray/core/dataset.py", line 769, in load_store
    obj = cls(variables, attrs=attributes)
  File "/home/avmo/.pyenv/versions/pymech/lib/python3.9/site-packages/xarray/core/dataset.py", line 749, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
  File "/home/avmo/.pyenv/versions/pymech/lib/python3.9/site-packages/xarray/core/merge.py", line 483, in merge_data_and_coords
    return merge_core(
  File "/home/avmo/.pyenv/versions/pymech/lib/python3.9/site-packages/xarray/core/merge.py", line 640, in merge_core
    dims = calculate_dimensions(variables)
  File "/home/avmo/.pyenv/versions/pymech/lib/python3.9/site-packages/xarray/core/dataset.py", line 203, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'y': length 6 on 'xmesh' and length 30 on {'x': 'x', 'y': 'y', 'z': 'z'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avmo/Sources/snek5000/pymech/pymech/dataset.py", line 57, in open_dataset
    return _open(path, **kwargs)
  File "/home/avmo/Sources/snek5000/pymech/pymech/dataset.py", line 81, in _open_nek_dataset
    raise NotImplementedError(
NotImplementedError: Opening dataset failed because you probably tried to open a field file with an unsupported mesh. The `pymech.open_dataset` function currently works only with cartesian box meshes. For more details on this, see https://github.com/eX-Mech/pymech/issues/31
```
